# Generated by Django 2.0 on 2020-02-28 21:38

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('idcard', models.CharField(max_length=32, null=True, unique=True)),
                ('password', models.CharField(default='zxcdsf789', max_length=128)),
                ('level', models.CharField(choices=[('本科', '本科'), ('专科', '专科')], default='本科', max_length=32)),
                ('major', models.CharField(choices=[('软件工程', '软件工程'), ('法学', '法学'), ('数学', '数学')], default='软件工程', max_length=32)),
                ('role', models.CharField(choices=[('student', '学生'), ('teacher', '教师'), ('administrator', '管理员')], default='student', max_length=32)),
                ('is_checked', models.BooleanField(default=False)),
                ('touxiang', models.ImageField(default='images/2019/12/touxiang_img.png', upload_to='images/%Y/%m')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户数据表',
                'verbose_name_plural': '用户数据表',
                'db_table': 'auth_user',
                'ordering': ['-last_updated_time'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(choices=[('软件工程', '软件工程'), ('法学', '法学'), ('数学', '数学')], default='软件工程', max_length=32)),
                ('level', models.CharField(choices=[('本科', '本科'), ('专科', '专科')], default='本科', max_length=32)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
                'ordering': ['-last_updated_time'],
            },
        ),
        migrations.CreateModel(
            name='ExamTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_template_name', models.CharField(max_length=32, unique=True)),
                ('exam_name', models.CharField(max_length=32, unique=True)),
                ('exam_th', models.IntegerField(default=0)),
                ('subject', models.CharField(choices=[('英语', '英语'), ('语文', '语文'), ('生物', '生物'), ('化学', '化学')], default='英语', max_length=32)),
                ('difficult', models.CharField(choices=[('简单', '简单'), ('一般', '一般'), ('困难', '困难'), ('极难', '极难')], default='一般', max_length=32)),
                ('exam_start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('exam_end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': '试卷模板',
                'verbose_name_plural': '试卷模板',
                'ordering': ['-last_updated_time'],
            },
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_name', models.CharField(max_length=128)),
                ('subject', models.CharField(choices=[('英语', '英语'), ('语文', '语文'), ('生物', '生物'), ('化学', '化学')], default='英语', max_length=32)),
                ('level', models.CharField(choices=[('本科', '本科'), ('专科', '专科')], default='本科', max_length=32)),
                ('major', models.CharField(choices=[('软件工程', '软件工程'), ('法学', '法学'), ('数学', '数学')], default='软件工程', max_length=32)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': '知识点',
                'verbose_name_plural': '知识点',
                'db_table': 'knowledge',
                'ordering': ['-last_updated_time'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=32, unique=True)),
                ('single_choice_num', models.IntegerField(default=0)),
                ('single_choice_score', models.IntegerField(default=0)),
                ('mul_choice_num', models.IntegerField(default=0)),
                ('mul_choice_score', models.IntegerField(default=0)),
                ('judge_num', models.IntegerField(default=0)),
                ('judge_score', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': '试卷方案',
                'verbose_name_plural': '试卷方案',
                'ordering': ['-last_updated_time'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.TextField()),
                ('option', models.TextField()),
                ('answer', models.CharField(max_length=8)),
                ('score', models.IntegerField()),
                ('subject', models.CharField(choices=[('英语', '英语'), ('语文', '语文'), ('生物', '生物'), ('化学', '化学')], default='英语', max_length=32)),
                ('question_type', models.CharField(choices=[('单选题', '单选题'), ('多选题', '多选题'), ('判断题', '判断题')], default='单选题', max_length=32)),
                ('difficult', models.CharField(choices=[('简单', '简单'), ('一般', '一般'), ('困难', '困难'), ('极难', '极难')], default='一般', max_length=32)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Knowledge')),
            ],
            options={
                'verbose_name': '问题',
                'verbose_name_plural': '问题',
                'db_table': 'question',
                'ordering': ['-last_updated_time'],
            },
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Plan'),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ExamTemplate'),
        ),
    ]
