# Generated by Django 2.0 on 2020-02-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_name',
            field=models.CharField(default='测试试卷', max_length=32),
        ),
        migrations.AddField(
            model_name='exam',
            name='question_id_ls',
            field=models.CharField(default="['1','2']", max_length=128),
        ),
    ]
