# Generated by Django 2.0 on 2020-02-29 21:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_exam_allot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='allot',
        ),
        migrations.AddField(
            model_name='exam',
            name='allot',
            field=models.ManyToManyField(blank=True, null=True, related_name='allot_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
