# Generated by Django 2.0 on 2020-03-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200301_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_describe',
            field=models.TextField(default=''),
        ),
    ]
