# Generated by Django 2.0 on 2020-03-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_exam_exam_describe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='question_id_ls',
            field=models.CharField(default="{'single_choice_id_ls': [], 'mul_choice_id_ls': [],'judge_id_ls': []}", max_length=128),
        ),
    ]
